version: "3"

services:
  apisix:
    image: apache/apisix:${APISIX_IMAGE_TAG:-3.2.2-debian}
    restart: always
    volumes:
      - ./apisix_conf/config.yaml:/usr/local/apisix/conf/config.yaml:ro
      - ./apisix_conf/apisix.yaml:/usr/local/apisix/conf/apisix.yaml:ro
      - ./custom-plugins:/opt/apisix/plugins:ro
    ports:
      - "9080:9080"
    environment:
      - GATEWAY_PORT=9080

  backend:
    build: ./upstream
    restart: always
    ports:
      - "9081:80"